### ISSUE TITLE
Use of Third Party libs

### ISSUE THREAD

**Issue by ellisonleao** [polyglotness/polyglotness#1]
how should we proceed on this case? Can we use third party libs on the projects?

**Comment by ervilis** [comment]
@ellisonleao I believe reinvent the wheel is so wrong that has no justification to do it :p So I think there is no problem.

**Comment by ellisonleao** [comment]
Not sure if the problem is more about reinventing the wheel. On some languages, we can easily implement the scenarios with no harm. Could be a great way of knowing how things are done instead of just using an easy abstraction layer. But, in some cases, i think the use of third party libs will be required. That's why i've opened this issue, so we can discuss the good vs bad of using those.

**Comment by ervilis** [comment]
@ellisonleao I agree.
I believe that it's okay for example use a third party lib of database connector (would be unnecessary rebuild the connector for each language, only this already would be a challenge).
On the other hand it would be very easy to use a third party lib to consume the API RESTFUL without using HTTP build-ins libraries of the language directly.

I believe that with this thought we can have a medium between reinvent the wheel and use third party libs.

**Comment by rochacbruno** [comment]
I think it is ok to use third party libs, since they are open source, there will be moderators which can ban abusive use of magic.

I think it is necessary to use those libs for:
1. http requests
2. data access
3. web development, handle of forms etc
4. GUI framework
5. Email
6. unittests
7. Deployment/automating (Make, Fabric etc)
8. JSON parsing
9. CLI arg parsing

The project idea is to motivate programmers to be polyglots and know how to program with 15 languages but also how to integrate and build the platform specific details. No problem using libs.

**Comment by ervilis** [comment]
@rochacbruno  +1

**Comment by ellisonleao** [comment]
Great! We Can add some mention about that on README. What do you think @rochacbruno ?

**Comment by rochacbruno** [comment]
:+1: @ellisonleao
