### ISSUE TITLE
Congrats validate, how to validate if the user that did?

### ISSUE THREAD

**Issue by avelino** [polyglotness/polyglotness#4]
```
Congrats! you are a Polyglot Programmer!
you will get a sticker and a t-shirt oferred by one of our sponsors!
```

As you think about validate that was the user who made the code itself to make a shirt?
The idea of winning t-shirt is pretty cool, but can pick up someone else's code that you've done and say that is mine.

**Comment by rochacbruno** [comment]
That is a good question, but there is some science behind that! 

I am developing the polyglotBot , the mind behind the polyglotness challenge, for every CANDIDATE the bot will monitor the commits and issues trough the github API and them, since the fitst story is implemented the bot will open new issues requiring new specs to be develop, a count of 3 new features and the mandatory tests will also be aleatory.

As it will take a long time to anyone (human) to develop this, we will have time to develop everything needed, the bot, the website, the logo and find some sponsor.

**Comment by avelino** [comment]
Great project!
